/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prolab;

import prolab.Oyuncupackage.Oyuncu;
import static prolab.Main.secim;

/**
 *
 * @author UMUT
 */
public class BaslangicEkrani extends javax.swing.JFrame {

    /**
     * Creates new form BaslangicEkrani
     */
    Oyuncu oyuncu = new Oyuncu();
    public BaslangicEkrani() {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        GozlukluButon = new javax.swing.JButton();
        TembelButon = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(640, 390));
        setPreferredSize(new java.awt.Dimension(650, 450));
        getContentPane().setLayout(null);

        jPanel1.setMinimumSize(new java.awt.Dimension(640, 390));
        jPanel1.setPreferredSize(new java.awt.Dimension(640, 391));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prolab/resimler/sirinlerdeki-gizli-mesajlari-gordunuz-mu-h1442126975.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setPreferredSize(new java.awt.Dimension(640, 320));

        GozlukluButon.setText("Gözlüklü Şirin");
        GozlukluButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GozlukluButonActionPerformed(evt);
            }
        });

        TembelButon.setText("Tembel Şirin");
        TembelButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TembelButonActionPerformed(evt);
            }
        });

        jLabel2.setText("Oynamak istediğiniz Şirini Seçiniz.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(GozlukluButon, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(TembelButon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(202, 202, 202))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TembelButon, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GozlukluButon, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 640, 390);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GozlukluButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GozlukluButonActionPerformed
        // TODO add your handling code here:
        oyuncu.setKarakterTur("Oyuncu");
        oyuncu.setKarakterAdi("GozlukluSirin");
        oyuncu.setKarakterID("Sirin1");
        oyuncu.setKonumX(5);
        oyuncu.setKonumY(6);
        oyuncu.setSkor(20);
        secim.setVisible(false);
        new OyunEkrani(oyuncu);
    }//GEN-LAST:event_GozlukluButonActionPerformed

    private void TembelButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TembelButonActionPerformed
        // TODO add your handling code here:
        oyuncu.setKarakterTur("Oyuncu");
        oyuncu.setKarakterAdi("TembelSirin");
        oyuncu.setKarakterID("Sirin2");
        oyuncu.setKonumX(5);
        oyuncu.setKonumY(6);
        oyuncu.setSkor(20);
        secim.setVisible(false);
        new OyunEkrani(oyuncu);
        System.out.println(oyuncu.getKarakterAdi());
    }//GEN-LAST:event_TembelButonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BaslangicEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BaslangicEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BaslangicEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BaslangicEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GozlukluButon;
    private javax.swing.JButton TembelButon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
