/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package songsfile;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Arthas
 */
public class adminPanel extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public adminPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adminSignNickNameText = new javax.swing.JTextField();
        adminSignEmailText = new javax.swing.JTextField();
        adminSignButton = new javax.swing.JButton();
        adminInfoLabel2 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        adminTurnBack = new javax.swing.JButton();
        adminSignPasswordText = new javax.swing.JPasswordField();
        adminBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("adminGiris/Kayit");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(adminSignNickNameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 202, 50));
        getContentPane().add(adminSignEmailText, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 202, 46));

        adminSignButton.setBackground(new java.awt.Color(0, 0, 0));
        adminSignButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        adminSignButton.setForeground(new java.awt.Color(255, 255, 255));
        adminSignButton.setText("Sign Up");
        adminSignButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminSignButtonMouseClicked(evt);
            }
        });
        getContentPane().add(adminSignButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 540, 140, 60));

        adminInfoLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        adminInfoLabel2.setText("Düzenleme Yapmak İçin Giriş Yapın");
        getContentPane().add(adminInfoLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 340, 80));

        jLabel20.setText(":NickName");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 80, -1));

        jLabel21.setText(":Email");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 80, -1));

        jLabel22.setText(":Password");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 80, -1));

        adminTurnBack.setBackground(new java.awt.Color(0, 0, 0));
        adminTurnBack.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        adminTurnBack.setForeground(new java.awt.Color(255, 255, 255));
        adminTurnBack.setText("<---");
        adminTurnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminTurnBackMouseClicked(evt);
            }
        });
        getContentPane().add(adminTurnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 590, -1, -1));
        getContentPane().add(adminSignPasswordText, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, 200, 50));

        adminBackground.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adminBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/40-402293_rock-nroll-vector-logo-rock-an-roll.png"))); // NOI18N
        getContentPane().add(adminBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void adminSignButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminSignButtonMouseClicked
        PreparedStatement ps = null;
        ResultSet rs = null;
        Connection con=connection.connect();       
        String signNickName;
        String signEmail;
        String signPassword;

        signNickName = adminSignNickNameText.getText();
        signEmail = adminSignEmailText.getText();
        signPassword = String.valueOf(adminSignPasswordText.getPassword());

        String query = "SELECT * FROM admin WHERE adminNickName=? AND adminEmail=? AND adminPassword=?";

        try {
            ps = con.prepareStatement(query);

            ps.setString(1, signNickName);
            ps.setString(2, signEmail);
            ps.setString(3, signPassword);
            
            adminMainPageAlbum ap = new adminMainPageAlbum();
            rs = ps.executeQuery();
            if (rs.next()) { 
                ap.setVisible(true);
                ap.pack();
                ap.setLocationRelativeTo(null);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "YANLIS MAIL ADRESİ YA DA PAROLA", "GIRIS BASARISIZ", 2);
            }
        } catch (Exception ex) {
            Logger.getLogger(adminPanel.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                ps.close();
                rs.close();
                con.close();
            } catch (Exception ex) {
               
            }

        }


    }//GEN-LAST:event_adminSignButtonMouseClicked

    private void adminTurnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminTurnBackMouseClicked
        new usersOradmin().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_adminTurnBackMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adminBackground;
    private javax.swing.JLabel adminInfoLabel2;
    private javax.swing.JButton adminSignButton;
    private javax.swing.JTextField adminSignEmailText;
    private javax.swing.JTextField adminSignNickNameText;
    private javax.swing.JPasswordField adminSignPasswordText;
    private javax.swing.JButton adminTurnBack;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    // End of variables declaration//GEN-END:variables

}
