/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package songsfile;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Arthas
 */
public class adminMainPageSarki extends javax.swing.JFrame implements TableModelListener {

    /**
     * Creates new form adminMainPage
     */
    public adminMainPageSarki() {
        initComponents();
        showSongs();
    }

    public ArrayList<AramaSarki> sarkiList() {
        ArrayList<AramaSarki> sarkiList = new ArrayList<>();
        Statement st = null;
        ResultSet rs = null;
        try {
            st = connection.connect().createStatement();
            String searchQuery = "SELECT * FROM 'songs'";
            rs = st.executeQuery(searchQuery);
            AramaSarki aramaSarki;
            while (rs.next()) {
                aramaSarki = new AramaSarki(
                        rs.getInt("songsid"),
                        rs.getString("songsName"),
                        rs.getString("songsDate"),
                        rs.getString("songsAuthor"),
                        rs.getString("songsAlbum"),
                        rs.getString("songsType"),
                        rs.getInt("songsTime"),
                        rs.getInt("songsCount")
                );
                sarkiList.add(aramaSarki);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        } finally {
            try {
                rs.close();
                st.close();
            } catch (Exception e) {

            }
        }

        return sarkiList;
    }

    private void showSongs() {
        ArrayList<AramaSarki> sonuc = sarkiList();
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        Object[] row = new Object[8];

        for (int i = 0; i < sonuc.size(); i++) {
            row[0] = sonuc.get(i).getSongsid();
            row[1] = sonuc.get(i).getSongsName();
            row[2] = sonuc.get(i).getSongsDate();
            row[3] = sonuc.get(i).getSongsAuthor();
            row[4] = sonuc.get(i).getSongsAlbum();
            row[5] = sonuc.get(i).getSongsType();
            row[6] = sonuc.get(i).getSongsTime();
            row[7] = sonuc.get(i).getSongsCount();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        scrollPane1 = new java.awt.ScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        sarkiSure = new javax.swing.JTextField();
        sarkiAd = new javax.swing.JTextField();
        sarkiTarih = new javax.swing.JTextField();
        sarkiYazar = new javax.swing.JTextField();
        sarkiAlbum = new javax.swing.JTextField();
        jLAbel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        resetButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        kaydetButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        turnBack = new javax.swing.JButton();
        sarkiDinlenme = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        sarkiTuru = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Şarkı ID", "Şarkı Ismi", "Tarih", "Sanatçı", "Albüm", "Tür", "Süre", "Dinlenme Sayısı"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        scrollPane1.add(jScrollPane1);

        getContentPane().add(scrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 540, 560));
        getContentPane().add(sarkiSure, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 280, 210, 40));
        getContentPane().add(sarkiAd, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 90, 190, 40));
        getContentPane().add(sarkiTarih, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 90, 210, 40));
        getContentPane().add(sarkiYazar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 190, 190, 40));
        getContentPane().add(sarkiAlbum, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 190, 210, 40));

        jLAbel.setForeground(new java.awt.Color(255, 255, 255));
        jLAbel.setText("Süre:");
        getContentPane().add(jLAbel, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 240, 190, 30));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Şarkı Adı:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 50, 170, 30));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tarih");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 50, 200, 30));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Sanatçı:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 150, 180, 30));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Albüm:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 160, 210, 30));

        resetButton.setBackground(new java.awt.Color(0, 0, 0));
        resetButton.setForeground(new java.awt.Color(255, 255, 255));
        resetButton.setText("Temizle");
        resetButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetButtonMouseClicked(evt);
            }
        });
        getContentPane().add(resetButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 530, 120, 50));

        deleteButton.setBackground(new java.awt.Color(0, 0, 0));
        deleteButton.setForeground(new java.awt.Color(255, 255, 255));
        deleteButton.setText("Sil");
        deleteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteButtonMouseClicked(evt);
            }
        });
        getContentPane().add(deleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 530, 110, 50));

        kaydetButton.setBackground(new java.awt.Color(0, 0, 0));
        kaydetButton.setForeground(new java.awt.Color(255, 255, 255));
        kaydetButton.setText("Kaydet");
        kaydetButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kaydetButtonMouseClicked(evt);
            }
        });
        getContentPane().add(kaydetButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 460, 120, 50));

        updateButton.setBackground(new java.awt.Color(0, 0, 0));
        updateButton.setForeground(new java.awt.Color(255, 255, 255));
        updateButton.setText("Güncelle");
        updateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateButtonMouseClicked(evt);
            }
        });
        getContentPane().add(updateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 460, 110, 50));

        turnBack.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        turnBack.setText("<---");
        turnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                turnBackMouseClicked(evt);
            }
        });
        getContentPane().add(turnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 600, 80, -1));
        getContentPane().add(sarkiDinlenme, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 370, 200, 40));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Dinlenme Sayısı:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 330, 190, 30));
        getContentPane().add(sarkiTuru, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 280, 190, 40));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Türü:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 250, 190, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/adminBackg.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 640));

        jMenu1.setBackground(new java.awt.Color(255, 255, 255));
        jMenu1.setText("Albüm Düzenle");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setBackground(new java.awt.Color(255, 255, 255));
        jMenu2.setText("Şarkı Düzenle");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu3.setBackground(new java.awt.Color(255, 255, 255));
        jMenu3.setText("Sanatçı Düzenle");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void resetButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetButtonMouseClicked

        sarkiAd.setText("");
        sarkiTarih.setText("");
        sarkiYazar.setText("");
        sarkiAlbum.setText("");
        sarkiTuru.setText("");
        sarkiSure.setText("");
        sarkiDinlenme.setText("");
    }//GEN-LAST:event_resetButtonMouseClicked

    private void deleteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteButtonMouseClicked
        PreparedStatement ps = null;

        try {
            int row = table.getSelectedRow();
            String value = (table.getModel().getValueAt(row, 0).toString());
            String Query = "DELETE FROM songs WHERE songsid=" + value;

            ps = connection.connect().prepareStatement(Query);

            ps.executeUpdate();
            if (ps.executeUpdate() > 1) {
                JOptionPane.showMessageDialog(null, "SARKI SILINDI");
            }

            DefaultTableModel model = (DefaultTableModel) table.getModel();
            model.setRowCount(0);
            showSongs();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        } finally {
            try {
                ps.close();
            } catch (Exception e) {

            }
        }
    }//GEN-LAST:event_deleteButtonMouseClicked

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        int i = table.getSelectedRow();
        TableModel model = table.getModel();
        sarkiAd.setText(model.getValueAt(i, 1).toString());
        sarkiTarih.setText(model.getValueAt(i, 2).toString());
        sarkiYazar.setText(model.getValueAt(i, 3).toString());
        sarkiAlbum.setText(model.getValueAt(i, 4).toString());
        sarkiTuru.setText(model.getValueAt(i, 5).toString());
        sarkiSure.setText(model.getValueAt(i, 6).toString());
        sarkiDinlenme.setText(model.getValueAt(i, 7).toString());
    }//GEN-LAST:event_tableMouseClicked

    private void kaydetButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kaydetButtonMouseClicked
        PreparedStatement ps = null;
        try {
            String Query = "INSERT INTO songs(songsName,songsDate,songsAuthor,songsAlbum,songsType,songsTime,songsCount)VALUES(?,?,?,?,?,?,?)";
            ps = connection.connect().prepareStatement(Query);

            ps.setString(1, sarkiAd.getText());
            ps.setString(2, sarkiTarih.getText());
            ps.setString(3, sarkiYazar.getText());
            ps.setString(4, sarkiAlbum.getText());
            ps.setString(5, sarkiTuru.getText());
            ps.setString(6, sarkiSure.getText());
            ps.setString(7, sarkiDinlenme.getText());

            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "SARKI EKLENDİ");

            DefaultTableModel model = (DefaultTableModel) table.getModel();
            model.setRowCount(0);
            showSongs();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        } finally {
            try {
                ps.close();
            } catch (Exception e) {

            }
        }
    }//GEN-LAST:event_kaydetButtonMouseClicked

    private void updateButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateButtonMouseClicked
        PreparedStatement ps = null;
        try {
            int row = table.getSelectedRow();
            String value = (table.getModel().getValueAt(row, 0).toString());
            String Query = "UPDATE songs SET songsName=?,songsDate=?,songsAuthor=?,songsAlbum=?,songsType=? ,songsTime=?,songsCount=? WHERE songsid =" + value;
            ps = connection.connect().prepareStatement(Query);

            ps.setString(1, sarkiAd.getText());
            ps.setString(2, sarkiTarih.getText());
            ps.setString(3, sarkiYazar.getText());
            ps.setString(4, sarkiAlbum.getText());
            ps.setString(5, sarkiTuru.getText());
            ps.setString(6, sarkiSure.getText());
            ps.setString(7, sarkiDinlenme.getText());

            ps.executeUpdate();
            if (ps.executeUpdate() > 1) {
                JOptionPane.showMessageDialog(null, "SARKI GUNCELLENDİ");
            }

            DefaultTableModel model = (DefaultTableModel) table.getModel();
            model.setRowCount(0);
            showSongs();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        } finally {
            try {
                ps.close();
            } catch (Exception e) {

            }
        }
    }//GEN-LAST:event_updateButtonMouseClicked

    private void turnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_turnBackMouseClicked
        new adminPanel().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_turnBackMouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        new adminMainPageAlbum().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        new adminMainPageSanatci().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenu3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminMainPageSarki.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminMainPageSarki.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminMainPageSarki.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminMainPageSarki.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminMainPageSarki().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel jLAbel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kaydetButton;
    private javax.swing.JButton resetButton;
    private javax.swing.JTextField sarkiAd;
    private javax.swing.JTextField sarkiAlbum;
    private javax.swing.JTextField sarkiDinlenme;
    private javax.swing.JTextField sarkiSure;
    private javax.swing.JTextField sarkiTarih;
    private javax.swing.JTextField sarkiTuru;
    private javax.swing.JTextField sarkiYazar;
    private java.awt.ScrollPane scrollPane1;
    private javax.swing.JTable table;
    private javax.swing.JButton turnBack;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables

    @Override
    public void tableChanged(TableModelEvent tme) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

}
