/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package songsfile;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Arthas
 */
public class adminMainPageSanatci extends javax.swing.JFrame implements TableModelListener {

    /**
     * Creates new form adminMainPage
     */
    public adminMainPageSanatci() {
        initComponents();
        showSanatci();
    }

    public ArrayList<AramaSanatci> sanatciList() {
        ArrayList<AramaSanatci> sanatciList = new ArrayList<>();
        Statement st = null;
        ResultSet rs = null;
        try {
            st = connection.connect().createStatement();
            String searchQuery = "SELECT * FROM author";
            rs = st.executeQuery(searchQuery);
            AramaSanatci aramaSanatci;
            while (rs.next()) {
                aramaSanatci = new AramaSanatci(
                        rs.getInt("authorid"),
                        rs.getString("authorName"),
                        rs.getString("authorCountry")
                );
                sanatciList.add(aramaSanatci);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        } finally {
            try {
                rs.close();
                st.close();
            } catch (Exception e) {

            }
        }

        return sanatciList;
    }

    private void showSanatci() {
        ArrayList<AramaSanatci> sonuc = sanatciList();
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        Object[] row = new Object[3];

        for (int i = 0; i < sonuc.size(); i++) {
            row[0] = sonuc.get(i).getAuthorid();
            row[1] = sonuc.get(i).getAuthorName();
            row[2] = sonuc.get(i).getAuthorCountry();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        scrollPane1 = new java.awt.ScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        sanatciAd = new javax.swing.JTextField();
        sanatciCountry = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        resetButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        kaydetButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        turnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sanatçı ID", "Sanatçı Ismi", "Sanatçı Ulke"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        scrollPane1.add(jScrollPane1);

        getContentPane().add(scrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 540, 560));
        getContentPane().add(sanatciAd, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 90, 210, 40));
        getContentPane().add(sanatciCountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 200, 210, 40));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Sanatçı Adı:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 50, 170, 30));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Sanatçı'nın Ülkesi:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 150, 200, 30));

        resetButton.setBackground(new java.awt.Color(0, 0, 0));
        resetButton.setForeground(new java.awt.Color(255, 255, 255));
        resetButton.setText("Temizle");
        resetButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetButtonMouseClicked(evt);
            }
        });
        getContentPane().add(resetButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 400, 120, 50));

        deleteButton.setBackground(new java.awt.Color(0, 0, 0));
        deleteButton.setForeground(new java.awt.Color(255, 255, 255));
        deleteButton.setText("Sil");
        deleteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteButtonMouseClicked(evt);
            }
        });
        getContentPane().add(deleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 400, 120, 50));

        kaydetButton.setBackground(new java.awt.Color(0, 0, 0));
        kaydetButton.setForeground(new java.awt.Color(255, 255, 255));
        kaydetButton.setText("Kaydet");
        kaydetButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kaydetButtonMouseClicked(evt);
            }
        });
        getContentPane().add(kaydetButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 340, 120, 50));

        updateButton.setBackground(new java.awt.Color(0, 0, 0));
        updateButton.setForeground(new java.awt.Color(255, 255, 255));
        updateButton.setText("Güncelle");
        updateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateButtonMouseClicked(evt);
            }
        });
        getContentPane().add(updateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 340, 120, 50));

        turnBack.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        turnBack.setText("<---");
        turnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                turnBackMouseClicked(evt);
            }
        });
        getContentPane().add(turnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 600, 80, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/adminBackg.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 640));

        jMenu1.setBackground(new java.awt.Color(255, 255, 255));
        jMenu1.setText("Albüm Düzenle");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setBackground(new java.awt.Color(255, 255, 255));
        jMenu2.setText("Şarkı Düzenle");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu3.setBackground(new java.awt.Color(255, 255, 255));
        jMenu3.setText("Sanatçı Düzenle");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void resetButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetButtonMouseClicked

        sanatciAd.setText("");
        sanatciCountry.setText("");
    }//GEN-LAST:event_resetButtonMouseClicked

    private void deleteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteButtonMouseClicked
        PreparedStatement ps = null;

        try {
            int row = table.getSelectedRow();
            String value = (table.getModel().getValueAt(row, 0).toString());
            String Query = "DELETE FROM author WHERE authorid=" + value;

            ps = connection.connect().prepareStatement(Query);

            ps.executeUpdate();
            if (ps.executeUpdate() > 1) {
                JOptionPane.showMessageDialog(null, "SANATCI SILINDI");
            }

            DefaultTableModel model = (DefaultTableModel) table.getModel();
            model.setRowCount(0);
            showSanatci();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        } finally {
            try {
                ps.close();
            } catch (Exception e) {

            }
        }
    }//GEN-LAST:event_deleteButtonMouseClicked

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        int i = table.getSelectedRow();
        TableModel model = table.getModel();
        sanatciAd.setText(model.getValueAt(i, 1).toString());
        sanatciCountry.setText(model.getValueAt(i, 2).toString());
    }//GEN-LAST:event_tableMouseClicked

    private void kaydetButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kaydetButtonMouseClicked
        PreparedStatement ps = null;
        try {
            String Query = "INSERT INTO author(authorName,authorCountry)VALUES(?,?)";
            ps = connection.connect().prepareStatement(Query);

            ps.setString(1, sanatciAd.getText());
            ps.setString(2, sanatciCountry.getText());

            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "SANATCI EKLENDİ");

            DefaultTableModel model = (DefaultTableModel) table.getModel();
            model.setRowCount(0);
            showSanatci();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        } finally {
            try {
                ps.close();
            } catch (Exception e) {

            }
        }
    }//GEN-LAST:event_kaydetButtonMouseClicked

    private void updateButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateButtonMouseClicked
        PreparedStatement ps = null;
        try {
            int row = table.getSelectedRow();
            String value = (table.getModel().getValueAt(row, 0).toString());
            String Query = "UPDATE author SET authorName=?,authorCountry=? WHERE authorid =" + value;
            ps = connection.connect().prepareStatement(Query);

            ps.setString(1, sanatciAd.getText());
            ps.setString(2, sanatciCountry.getText());


            ps.executeUpdate();
            if (ps.executeUpdate() > 1) {
                JOptionPane.showMessageDialog(null, "SANATCİ GUNCELLENDİ");
            }

            DefaultTableModel model = (DefaultTableModel) table.getModel();
            model.setRowCount(0);
            showSanatci();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        } finally {
            try {
                ps.close();
            } catch (Exception e) {

            }
        }
    }//GEN-LAST:event_updateButtonMouseClicked

    private void turnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_turnBackMouseClicked
        new adminPanel().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_turnBackMouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        new adminMainPageAlbum().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        new adminMainPageSarki().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminMainPageSanatci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminMainPageSanatci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminMainPageSanatci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminMainPageSanatci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminMainPageSanatci().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kaydetButton;
    private javax.swing.JButton resetButton;
    private javax.swing.JTextField sanatciAd;
    private javax.swing.JTextField sanatciCountry;
    private java.awt.ScrollPane scrollPane1;
    private javax.swing.JTable table;
    private javax.swing.JButton turnBack;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables

    @Override
    public void tableChanged(TableModelEvent tme) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

}
