/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package songsfile;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Arthas
 */
public class userPanel extends javax.swing.JFrame {

    int uyelikType = 0;

   static private String kullanıcıAdi;

   public String getKullanıcıAdi() {
        return kullanıcıAdi;
    }

    /**
     * @param kullanıcıAdi the kullanıcıAdi to set
     */
    public void setKullanıcıAdi(String kullanıcıAdi) {
        this.kullanıcıAdi = kullanıcıAdi;
    }

    /**
     * Creates new form userPanel
     */
    public userPanel() {
     
        initComponents();
    }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        userRegisterEmailText = new javax.swing.JTextField();
        userRegisterNickNameText = new javax.swing.JTextField();
        userRegisterButton = new javax.swing.JButton();
        userSignNickNameText = new javax.swing.JTextField();
        userSignEmailText = new javax.swing.JTextField();
        userSignButton = new javax.swing.JButton();
        userInfoLabel2 = new javax.swing.JLabel();
        userInfoLabel1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        userNormal = new javax.swing.JRadioButton();
        userRegisterPasswordText = new javax.swing.JPasswordField();
        userRegisterRePasswordText = new javax.swing.JPasswordField();
        userPremium = new javax.swing.JRadioButton();
        userSignPasswordText = new javax.swing.JPasswordField();
        userTurnBack = new javax.swing.JButton();
        userBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(userRegisterEmailText, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 202, 46));
        getContentPane().add(userRegisterNickNameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 202, 50));

        userRegisterButton.setBackground(new java.awt.Color(153, 0, 255));
        userRegisterButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        userRegisterButton.setForeground(new java.awt.Color(255, 153, 204));
        userRegisterButton.setText("Register");
        userRegisterButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 0), new java.awt.Color(51, 153, 255), new java.awt.Color(255, 0, 51), new java.awt.Color(255, 51, 204)));
        userRegisterButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userRegisterButtonMouseClicked(evt);
            }
        });
        getContentPane().add(userRegisterButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 530, 140, 60));
        getContentPane().add(userSignNickNameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 230, 202, 50));
        getContentPane().add(userSignEmailText, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 300, 202, 46));

        userSignButton.setBackground(new java.awt.Color(255, 153, 255));
        userSignButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        userSignButton.setForeground(new java.awt.Color(153, 0, 255));
        userSignButton.setText("Sign Up");
        userSignButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userSignButtonMouseClicked(evt);
            }
        });
        getContentPane().add(userSignButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 450, 140, 60));

        userInfoLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        userInfoLabel2.setForeground(new java.awt.Color(255, 255, 255));
        userInfoLabel2.setText("Hesabınız Var Mı?Giriş Yapın.");
        getContentPane().add(userInfoLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 120, 280, 80));

        userInfoLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        userInfoLabel1.setForeground(new java.awt.Color(255, 255, 255));
        userInfoLabel1.setText("Henüz Üye Değil Misiniz?");
        getContentPane().add(userInfoLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 260, 80));

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Password:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 80, -1));

        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText(":Password");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 390, 80, -1));

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText(":NickName");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 250, 80, -1));

        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText(":Email");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 320, 80, -1));

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("RePassword:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 100, -1));

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Email:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 80, -1));

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("NickName:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 80, -1));

        userNormal.setBackground(new java.awt.Color(255, 204, 0));
        buttonGroup.add(userNormal);
        userNormal.setForeground(new java.awt.Color(255, 255, 255));
        userNormal.setText("Normal Üyelik");
        getContentPane().add(userNormal, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 480, -1, 20));
        getContentPane().add(userRegisterPasswordText, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 200, 50));
        getContentPane().add(userRegisterRePasswordText, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, 200, 50));

        userPremium.setBackground(new java.awt.Color(255, 102, 51));
        buttonGroup.add(userPremium);
        userPremium.setForeground(new java.awt.Color(255, 255, 255));
        userPremium.setText("Premium Üyelik");
        userPremium.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 51)));
        getContentPane().add(userPremium, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, -1, -1));
        getContentPane().add(userSignPasswordText, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 370, 200, 50));

        userTurnBack.setBackground(new java.awt.Color(255, 102, 0));
        userTurnBack.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        userTurnBack.setForeground(new java.awt.Color(255, 255, 0));
        userTurnBack.setText("<---");
        userTurnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userTurnBackMouseClicked(evt);
            }
        });
        getContentPane().add(userTurnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 590, -1, -1));

        userBackground.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/b2.png"))); // NOI18N
        getContentPane().add(userBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userRegisterButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userRegisterButtonMouseClicked
        PreparedStatement ps = null;
        ResultSet rs = null;

        String registerNickName;
        String registerEmail;
        String registerPassword;
        String registerRePassword;

        registerNickName = userRegisterNickNameText.getText();
        kullanıcıAdi=registerNickName;
        System.out.println(kullanıcıAdi);
        registerEmail = userRegisterEmailText.getText();
        registerPassword = String.valueOf(userRegisterPasswordText.getPassword());
        registerRePassword = String.valueOf(userRegisterRePasswordText.getPassword());

        Connection con = connection.connect();
        if (userPremium.isSelected()) {
            uyelikType = 1;
            JOptionPane.showMessageDialog(null, "ÖDEME İÇİN YÖNLENDİRİLECEKSİNİZ.LÜTFEN BEKLEYİNİZ.");
        } else if (userNormal.isSelected()) {
            uyelikType = 0;
        }

        if (registerNickName.equals("")) {
            JOptionPane.showMessageDialog(null, "ADINIZI GIRINIZ!");
        } else if (registerPassword.equals("")) {
            JOptionPane.showMessageDialog(null, "SIFRENIZI GIRINIZ!");
        } else if (mailkontrol(registerEmail)) {
            JOptionPane.showMessageDialog(null, "BU MAIL ADRESI ZATEN KULLANIMDA!");
        } else if (!registerPassword.equals(registerRePassword)) {
            JOptionPane.showMessageDialog(null, "SIFRELER ESLESMİYOR!");
        } else {

            String query = "INSERT INTO 'users'( 'usersNickName', 'usersEmail', 'usersPassword','usersSubscription') VALUES (?,?,?,?)";
            try {
                ps = con.prepareStatement(query);

                ps.setString(1, registerNickName);
                ps.setString(2, registerEmail);
                ps.setString(3, registerPassword);
                ps.setInt(4, uyelikType);

               userMainPage as = new userMainPage();
                if (ps.executeUpdate() > 0) {
                    JOptionPane.showMessageDialog(null, "KULLANICI EKLENDI!");
                    as.setVisible(true);
                    this.dispose();
                    this.setVisible(false);
                    
                }

            } catch (Exception ex) {
                Logger.getLogger(adminPanel.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                try {
                    ps.close();
                    rs.close();
                    con.close();
                } catch (Exception ex) {

                }

            }
        }
    }//GEN-LAST:event_userRegisterButtonMouseClicked
    public boolean mailkontrol(String mail) {
        PreparedStatement ps = null;
        ResultSet rs = null;
        boolean kontrol = false;
        String query = "SELECT * FROM 'users' WHERE 'usersEmail' =?";

        Connection con = connection.connect();
        try {
            ps = con.prepareStatement(query);
            ps.setString(1, mail);

            rs = ps.executeQuery();

            if (rs.next()) {
                kontrol = true;
            }
        } catch (Exception ex) {
            Logger.getLogger(userPanel.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                ps.close();
                rs.close();
                con.close();
            } catch (Exception ex) {

            }

        }
        return kontrol;
    }
    private void userSignButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userSignButtonMouseClicked
        PreparedStatement ps = null;
        ResultSet rs = null;
        Connection con = connection.connect();

        String signNickName;
        String signEmail;
        String signPassword;
        
        signNickName = userSignNickNameText.getText();
        kullanıcıAdi=signNickName;
        
        System.out.println(kullanıcıAdi);
        signEmail = userSignEmailText.getText();
        signPassword = String.valueOf(userSignPasswordText.getPassword());

        String query = "SELECT * FROM 'users' WHERE usersNickName =? AND usersEmail =? AND usersPassword =?";

        try {
            ps = con.prepareStatement(query);

            ps.setString(1, signNickName);
            ps.setString(2, signEmail);
            ps.setString(3, signPassword);
            userMainPage as = new userMainPage();
            rs = ps.executeQuery();
          
            if (rs.next()) {
                
                as.setVisible(true);
                as.pack();
                as.setLocationRelativeTo(null);
                /* as.setExtendedState(JFrame.MAXIMIZED_BOTH);
                as.isimetiketi.setText("Welcome < " + isim +" >");*/

                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "GIRIS BASARISIZ");
            }
        } catch (Exception ex) {
            Logger.getLogger(adminPanel.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                ps.close();
                rs.close();
                con.close();
            } catch (Exception ex) {

            }

        }
       

    }//GEN-LAST:event_userSignButtonMouseClicked

    private void userTurnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userTurnBackMouseClicked
        new usersOradmin().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_userTurnBackMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userPanel().setVisible(true);
            }
        });
        
    }
   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel userBackground;
    private javax.swing.JLabel userInfoLabel1;
    private javax.swing.JLabel userInfoLabel2;
    private javax.swing.JRadioButton userNormal;
    private javax.swing.JRadioButton userPremium;
    private javax.swing.JButton userRegisterButton;
    private javax.swing.JTextField userRegisterEmailText;
    private javax.swing.JTextField userRegisterNickNameText;
    private javax.swing.JPasswordField userRegisterPasswordText;
    private javax.swing.JPasswordField userRegisterRePasswordText;
    private javax.swing.JButton userSignButton;
    private javax.swing.JTextField userSignEmailText;
    private javax.swing.JTextField userSignNickNameText;
    private javax.swing.JPasswordField userSignPasswordText;
    private javax.swing.JButton userTurnBack;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the kullanıcıAdi
     */
  
    

}
